# Generated by Django 4.2.6 on 2023-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_reservation_description_alter_reservation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('operador', 'Operador'), ('admin', 'Admin')], default='cliente', max_length=20),
        ),
    ]
