# Generated by Django 4.1.3 on 2023-11-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_is_admin_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locker_reservation', to='base.reservation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='state',
            field=models.IntegerField(choices=[(0, 'Cargando'), (1, 'Cargado'), (2, 'Confirmado')], default=0),
        ),
    ]
