# Generated by Django 4.1.3 on 2023-11-20 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_locker_reservation_reservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_reservations', to='base.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operador_reservations', to='base.user'),
        ),
    ]
