# Generated by Django 4.1.3 on 2023-11-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_reservation_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='users',
            field=models.ManyToManyField(related_name='reservations', to='base.user'),
        ),
    ]
