# Generated by Django 4.2.6 on 2023-11-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ecommerce_rename_description_reservation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='station',
            name='name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='key',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ecommerce',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
