# Generated by Django 4.2.6 on 2023-11-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_locker_name_alter_reservation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='horaCancelacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='horaCarga',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='horaConfirmacionOperador',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='horaConfirmacionReserva',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='horaDescarga',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='horaFinalizacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='conexion',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
