# Generated by Django 4.1.3 on 2023-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_reservation_identificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='identificador',
            field=models.IntegerField(default=67682, editable=False),
        ),
    ]
