# Generated by Django 4.2.6 on 2023-11-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_locker_name_alter_reservation_identificador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='identificador',
            field=models.IntegerField(default=56891, editable=False),
        ),
    ]
