# Generated by Django 4.2.6 on 2023-11-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_reservation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='station',
            field=models.CharField(default='ValorPorDefecto', max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='identificador',
            field=models.IntegerField(default=48595, editable=False),
        ),
    ]
